version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenhash_backend
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3 # Persist the SQLite database
      - ./blockchain/ml:/app/blockchain/ml # Ensure ML models are mounted
    environment:
      - DEBUG=True # Set to False in production
      - DJANGO_ALLOWED_HOSTS=* # Configure as needed for production
      - PINATA_JWT=YOUR_PINATA_JWT # Replace with your actual Pinata JWT
      - CONTRACT_ADDRESS=YOUR_CONTRACT_ADDRESS # Replace with your actual contract address
      - BLOCKCHAIN_PROVIDER=http://host.docker.internal:7545 # For Ganache running on the host. Adjust if Ganache is containerized or on a different URL.
      - ABI_PATH=blockchain/contracts/GreenHashABI.json # Relative path inside the backend container
    networks:
      - greenhash_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: greenhash_frontend
    ports:
      - "3000:80" # Map Nginx port 80 to host port 3000
    depends_on:
      - backend
    networks:
      - greenhash_net
    # It's good practice to also set environment variables for the frontend if it needs to know the backend URL
    # For example, if your React app fetches data from http://localhost:8000/api,
    # you'd want to make this configurable.
    # environment:
    #   - REACT_APP_API_URL=http://backend:8000/api

networks:
  greenhash_net:
    driver: bridge

volumes:
  db_data: # Define a named volume for the database if not using a local file path like ./db.sqlite3
